server:
  port: 9876

spring:
  application:
    name: URL Shortner Service

domain:
  url: http://srt.y/

hash-algorithm: SHA3-256

duid-server: http://localhost:9009/duid/

cache:
  url: "192.168.0.104"
  port: 6399

expiry-time: 86400

database:
  url: "jdbc:postgresql://192.168.0.104:26257/url_shortner"
  username: "root"
  password: "root"
  driver: "org.postgresql.Driver"
  modelPackage: "org.data.model"

event-db:
  driver: "postgresql"
  host: "192.168.29.174"
  port: 5432
  user: "postgres"
  password: "password"
  database: "postgres"
  poolSize: 5
  maxIdleTime: 1000
